cmd: Assert permission for `secrets-dir`
Before using fioconfig operations, we need to ensure we have permission
to extract files into the secrets directory. This command will produce
an error like:
```
$ ./bin/fioup config-extract
ERROR: Unable to create files in `secrets-dir`: open /run/secrets/.test-writeable: permission denied
```

Signed-off-by: Andy Doan <andy@foundries.io>